### ISSUE TITLE
Zone names are not displayed if no waypoint data exists

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#129]
Source: [WowAce](https://www.wowace.com/projects/rarity?comment=1957)
> Does anyone understand why (f.e. in Battle Pets section) for Brinstone Algan I see the correct zone (Nazjatar) but for Wriggler, Budding Algan and several other battle pets, the zone is empty. When I check the settings for those battle pets, they do not look different from the ones, where the Zone is displayed properly.

**Comment by godejord** [comment]
Has this changed over the past years? There are plenty items without any waypoints/coordinates that still show their respective zones as long as the zone id is set. I.e. all the items from paragon reputation caches etc.

The items the user is referring to doesn't have the zone id set either, but that's somewhat covered in #130. :)

**Comment by Duckwhale** [comment]
I think "waypoint data" refers to the ``coordinates`` entry, regardless of whether it only consists of a ``mapID``.

If there isn't any such field, I would expect no zone to be displayed if true, and otherwise that Rarity attempts to display the zone based by looking up the ``zoneText`` via ``LibBabble`` (IIRC).
