### ISSUE TITLE
Review item DB (and DB maintenance helper)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#152]
Tasks:

- [x] Move items to separate files, based on category/expansion
- [x] Check drop rates (wowhead API/script to find mismatches?)
- [x] Add missing waypoint data (so that the zone is displayed ingame)
- [x] Add defeat detection wherever it's missing
- [x] Clean up DB maintenance helper (verification routine)

**Comment by SacredDuckwhale** [comment]
Related WowAce issue: https://www.wowace.com/projects/rarity/issues/467

**Comment by Duckwhale** [comment]
Item DB is already refactored (well, sort of) in https://github.com/WowRarity/Rarity/issues/86. While not ideal, for the purposes of this issue it'll do.

**Comment by Duckwhale** [comment]
wowhead tools are already moved to https://github.com/WowRarity/Rarity/issues/74.

**Comment by Duckwhale** [comment]
Missing waypoint data is covered by https://github.com/WowRarity/Rarity/issues/169.

**Comment by Duckwhale** [comment]
DBMH stuff exists here: https://github.com/WowRarity/Rarity/issues/169

**Comment by Duckwhale** [comment]
Defeat detection should also be covered by that same issue, hopefully. If not, it's listed there so I'll create a separate issue for it later and it won't be forgotten.
