### ISSUE TITLE
Achievement popup text for items using the collection method isn't set correctly

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#164]
> if item and item.method and item.method == CONSTANTS.DETECTION_METHODS.COLLECTION
This variable (in the GUI code) is never set. Either it was broken before the last refactoring pass or I copy/pasted stuff incorrectly.

Right now I don't have time to look into this, and it's not a very high priority. Therefore I'm leaving this as a reminder. I'd assume the popup simply displays the regular text instead of one specific to the collection.

Example: WOD Tanaan sabercat reputation. Those items could be affected by this problem.

**Comment by godejord** [comment]
I am not sure which text this refers to, but as mentioned on Discord, I triggered this achievement toast while debugging something else on a collection item. As I completed the criteria, the achievement toast got set off and it all [looks](https://imgur.com/a/ES2dQuf) as expected to me. The announcement also got fired, allthough I forgot to take a screenshot of it

**Comment by Duckwhale** [comment]
I believe this issue refers to this portion of the code: https://github.com/WowRarity/Rarity/blob/c316040322c1964bbfc1611a79a9dd4dc182feb7/Core/GUI/FauxAchievementPopup.lua#L84-L85

Since the ``item`` variable is never set, the branch won't be executed ever. Instead of "Collection complete", the default text is displayed, which can be seen on the screenshot you provided.

**Comment by Duckwhale** [comment]
The screenshot actually confirms the validity of the issue, so I update the status to reflect this.

**Comment by Duckwhale** [comment]
Fixed via 85befd25bb127dd47278179c4208d45037272e4b. It's not a great fix, but it's good enough for the time being.
