### ISSUE TITLE
Refactor Database Maintenance Helper (prototype) to implement a streamlined Validation API

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#169]
* Required fields need to exist, and be named consistently (Id vs ID vs id, etc.)
* Types should be consistent, as well. Right now they're really not, which has caused multiple bugs
* Some fields may be obsolete or could be done away with? (Personal Loot related, I suppose)
* All items should have zones assigned so the tooltip doesn't just show an empty entry
* Waypoints themselves are optional, but should also use the UiMapIDs as constants, and not have hardcoded values like they do now
* Some zones may be missing subzones, which could be especially problematic for the fishing detection. Is there an automatic way of finding out which? May be able to use HereBeDragons migration API from back when Blizzard switched to UiMapIDs
* The existing code is a mess, as it was merely a quick prototype
* Add a button to the UI where it can be run manually?
* Defeat detection? Not sure if this is easy to validate...
* Output in a scrolling frame, instead of in chat? There are so many items that it can't even be read
* Maybe display a summary, as well? Something like X failed, Y succeeded, Z warnings?
* It should be possible to check custom items to avoid errors like the one caused by adding empty item data as a "custom" item (separate issue)

**Comment by SacredDuckwhale** [comment]
Related WowAce issue: https://www.wowace.com/projects/rarity/issues/467

**Comment by Duckwhale** [comment]
I'm thinking what would make more sense is to have a separate ``Validation`` API. This could implement methods to validate entire groups as well as individual entries.

The basic idea of the original prototype was indeed not bad, but it would benefit from some streamlining. Something like the [JOI API](https://joi.dev/api/) (but without the ugly JavaScript semantics) perhaps?

In this spirit, I'll refocus this issue to actually refactor the DB maintenance helper and implement the ``Validation`` API.

**Comment by Duckwhale** [comment]
Also, I know the prototype shouldn't have been merged into master in the current state, but it's too late now so we'll just to deal with it :zany_face:

**Comment by Duckwhale** [comment]
And with "we", I mean "I". I did the thing, so I'll have to clean it up, too.
