### ISSUE TITLE
Selectively disabling tracking for specific classes doesn't appear to be working

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#182]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/397)
> When tracking for armor class restricted items and fill in the kill statistics, Rarity tracks all characters, no matter of its armor. For example, I've created a tracker for Garrosh's plate shoulders and only want to track them with a plate class.

**Comment by FuxieDK** [comment]
Not just armor, also other items, e.g. <Illusion: Rune of Razorice> from LK is tracked on all my toons, even though it's disabled for all but DKs.

**Comment by SacredDuckwhale** [comment]
Yup, I actually forgot to add the report from WowAce ([Link](https://www.wowace.com/projects/rarity/issues/446)). I'll have to see if I can reproduce it, most likely something minor broke and it can be easily repaired.

**Comment by SacredDuckwhale** [comment]
Confirmed and fixed as of 9d2b1e54322fba802912008772d052441c881415.

**Comment by FuxieDK** [comment]
Also tracked <Illusion of Razorice> on same paladin. Didn't bother with picture, as it was only a few minutes after Valithria

**Comment by SacredDuckwhale** [comment]
Hmm. It appears that the detection based on kill statistics (achievement criteria) does indeed not check for disabled classes, and I doubt it ever has. This might be tricky, I'll have to think about it some more.

**Comment by Duckwhale** [comment]
Will have to look into this again, but I currently don't have time :/

**Comment by Duckwhale** [comment]
This (or a similar) issue has again been reported on Discrd. In this specific instance, transmog items were tracked on the wrong classes. Import string:

> <@!139783576307630080> Az1TCv8CakGV9ZCUXopimyjNpKoOE8wW1WNSbirqFySV21K5DLWTZC/arWQ/qfxUqmGUNI4qzlPCUEEGk6rhKjooclriGKFziiwkWqrSYkq0XKoeUtRTsExSz6VMVGgqlcmSTFd1kcJVQXmmwnVIbBTKVkFVm5UyjVIfqcpXofpMlfouqDRSyDeKjIbUeKrkJMQtSHJNwT1BxUpIqtZCUvwWmCIdoTzuGh2VSEd4ixMTEGfMhA4/OqgIcgcgVKUJljmOBb05F1qjI4xGclFGIb7IURLi6V5kv5SEeLr+3ZyhJISSP42IoiTMyWdQEiBKc1KUhChMOeNSEkIXMcBR8glL6DBB4vx1+mDT6R+NdXpzb9FeyHV612NMWKfW6KhEqqP2ZE1UNdVRewYT1UF11FNtorKp6snkGax8goYWloYZMw3WYZqmw+SZBqunNnFDZU+EstoLS8Nj2baioeRfcKOjEm1KPgF7nUH/AZSE8rhDKip7sIeBT1XTEd7ixATEGTOhw48OKoLcAQhVaYJljmNBb86F1ugIo5FclFGIL3KUhHi6F9kvJSGern83ZygJoeRPI6IoCXPyGZQEiNKcFCUhClPOuJSE0EUMcJR8whI6TJC9oOG+6fTBptM/Guv0sg+CqgsejXvCOrVGRyVSHYfoyfIJGlpYGqYSrYSy2gtLw2PZtqKh5F9wo6MSbUo+AXudQf8BlITyuEMqKnsQ7YlPddAR3uLEBMQZM6HDjw4qgtwBCFVpgmWOY0FvzoXW6AijkVyUUYgvcpSEeLoX2S8lIZ6ufzdnKAmh5E8joigJc/IZlASI0pwUJSEKU864lITQRQxwlHzCEjpMiOVCh8PtAxRv9Ov05rI0NGGdWqOjEqmOQxQ9fIKGFpaGGfNks1ZT1jOItmiyrYfIDdVgJZTVXlgaHsu2FQ0l/wGCGx2VaFPyCdjrDPqnJJTHHVJR2YPoGfhUNh3hLU5MQJwxEzr86KAiyB2AUJUmWOY4FvTmXGiNjjAayUUZhfgiR0mIp3uR/VIS4un6d3OGkhBK/jQiipIwJ59BSYAozUlREqIw5YxLSQhdxP8CR8knLKHDhFiO4lWWt05vLNx7W+j05qDkjbBOrdFRiVTHUU8HVU1Vm6bsIPIJGlpYGmYsK4qTtRbro/bY1sP2cENlmwhltReWhseybUVDyb/gRkcl2pR8AvY6g/4pCeVxh1RU9uDJTnyqgY7wFicmIM6YCR1+dFAR5A5AqEoTLHMcC3pzLrRGRxiN5KKMQnyRoyTE073IfikJ8XT9uzlDSQglfxoRRUmYk8+gJECU5qQoCVGYcsalJIQuYoCj5BOW0GGCD6U0rNMHm07/AWis08+l8hb6SqcH3J94PWGdWqOjEqnEyT7Emk/Q0MLSMGMeq12Ldi1Oouk4rPXEDdVgJZTVXlgaHsu2FQ0l/wGCGx2VaFPyCdjrDPqnJJTHHVJR2YNnOvhUooeO8BYnJiDOmAkdfnRQEeQOQKhKEyxzHAt6cy60RkeIwpQzLiUhnu5F9ktJCCV/GhFFSZiTz6AkhC5igKMkxNP17+YMJWE05l1FYcoZl5aE0UguyijEFzlKAkRpToqST1hChwnwQo9KYqHClU5vzlFeQxPWqTU6KpFKnGxPLfIJGlpYGqYarISy2gtLw2PZtqKh5F9wo6MSbUo+AXudQf8BlITyuEMqKnvIilk+lTjREd7ixATEGTOhw48OKoLcAQhVaYJljmNBb86F1ugIo5FclFGIL3KUhHi6F9kvJSGern83ZygJoeRPI6IoCXPyGZQEiNKcFCUhClPOuJSE0EUMcJR8whI6TAgft9fpg02nfzTW6X15EG5Z3jq9ucdNw+sJ69QaHZVIdRz1dFDVVLVpyg4i1UFVTybPNPEJGlpYGmZssG3TZK1NpsFq29MwcENlT4Sy2gtLw2PZtqKh5F9wo6MSbUo+AXudQf8BlITyuEMqKnvIerJ8qtpKR3iLExMQZ8yEDj86qAhyByBUpQmWOY4FvTkXWqMjjEZyUUYhvshREuLpXmS/lIR4uv7dnKEkhJI/jYiiJMzJZ1ASIEpzUpSEKEw541ISQhcxwFHyCUvoMCF83L7D65tOH2w6/aOxTi/zsiqdfsSroBYvwjq1RkclUh1HbRKpaqraNGUHE5+goYWlYSrbSiirvbA0PJZtKxpK/gU3OirRpuQTsNcZ9E9JKI87pKKyh0Gc+FS1SEd4ixMTEGfMhA4/OqgIcgcgVKUJljmOBb05F1qjI4xGclFGIb7IURLi6V5kv5SEeLr+3ZyhJISSP42IoiTMyWdQEiBKc1KUhChMOeNSEkIXMcBR8glL6DABNUFVBE2n92Nv77K8G2GdWqOjEqnEyfbUIp+goYWlYcY82azVlPUMoi2abOshckM1WAlltReWhseybUVDyb/gRkcl2pR8AvY6g/4pCeVxh1RUdtZqT3w+oRXvJTxKjwk3htSh0Q5vDw/1VrXeG1ka6lCTwgmHYIlS8orKJB58Eg==

Will have to investigate if this may be related to kill statistics or a separate problem.

**Comment by Duckwhale** [comment]
I don't think it's feasible to "ignore" certain attempts for items that use kill statistics, as we'd have to keep track of the number of attempts that shouldn't count. There are many ways for that to go wrong, particularly with accountwide statistics and when players reset/lose their settings, so that we have to sync with their stats again and we won't have the number of "ignored" attempts.

And of course adapting the code to modify the accountwide stats bookkeeping could be tricky/break backwards compat.

Unless someone comes up with a proposal and/or wants to implement more advanced bookkeeping, that's a "nope" from me.
