### ISSUE TITLE
Duplicate attempts are being counted for Invincible's Reins

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#213]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/446)

I accidentally managed to reproduce it while trying to troubleshoot an unrelated issue (https://github.com/SacredDuckwhale/Rarity/issues/182). Here is the debug log:

![https://i.imgur.com/cGSTGfy.png](https://i.imgur.com/cGSTGfy.png)

![https://i.imgur.com/UUQAgn4.png](https://i.imgur.com/UUQAgn4.png)

![https://i.imgur.com/BzZB3WY.png](https://i.imgur.com/BzZB3WY.png)

![https://i.imgur.com/76HwmBw.png](https://i.imgur.com/76HwmBw.png)

**Comment by SacredDuckwhale** [comment]
Also, is it possible this might be related to https://github.com/SacredDuckwhale/Rarity/issues/174?

**Comment by Duckwhale** [comment]
The problem is that `Rarity.npcs_to_items[36597]` contains all items that are related to the boss, and then `OnCombat` blindly adds attempts for all of them while handling `UNIT_DIED`. Invincible uses this event with a fake NPC ID, but also uses kill statistics (which adds the second attempt). Clearly this isn't right. I suppose switching to `SPECIAL` instead of `BOSS` might help?

Source: [Core/EventHandlers.lua](https://github.com/WowRarity/Rarity/blob/6f9c75d01bd0922aaa1fa7e6d62d5d099fd7856a/Core/EventHandlers.lua#L394-L429)

Now, there are still a few questions:

1. Why are the pets (that use `NPC` and kill statistics) only counting once?
2. Does the problem occur always or only "sometimes" (see #174)?
3. Should items with kill statistics use `NPC`, `BOSS`, or `SPECIAL`? (check the DB for other items?)

**Comment by Duckwhale** [comment]
I suppose the answers to the above questions are:

1. Because the duplicate attempt comes from the `UNIT_DIED` event handler, i.e. the `BOSS` detection method (combat log events)
2. It should happen every time, as long as `UNIT_DIED` is triggered by the game
3. All items seem to be using `BOSS` so changing the `UNIT_DIED` event handler is likely easiest

The simplest fix would be to just check if the item has statistics and then not add attempts for a `UNIT_DIED` event.
