### ISSUE TITLE
Revisit tracking for Darkmoon Rabbit (pet)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#248]
I recently found this in my inbox:

> DMF Rabbit (1): I think the issue is that the only way to detect an attempt is via UNIT_DIED, but anyone on DMF Island sees that event even if they didn’t participate in combat, and there is no Statistic. One workaround would be to first detect any other combat event between you and the rabbit, but that doesn’t work for healers. It’s essentially unsupported since Rarity doesn’t detect loot toasts themselves. That said, maybe you have some idea of how to support it. Does WoW fire a “you defeated this boss” event for that rabbit now? If so, you could add Rarity support for that event, which currently is not implemented. That’s an example of an event which did not exist in 2011 when this add-on was created. Defeat detection was quite complicated (I should know, I wrote a lot of boss mods in 2008-2010 haha.)

Source: Allara

Not sure if the client now supports an event that could be used to track the rabbit, or if there are creative solutions I didn't see back when I first looked into this (years ago). It might be worth revisiting, as much has changed since then.

**Comment by SacredDuckwhale** [comment]
FAQ:
> Darkmoon Rabbit isn't supported
Due to limitations in the Blizzard API for add-ons, this item cannot be supported.

If we can get around this, the paragraph should obviously be removed.

**Comment by Duckwhale** [comment]
It seems this is now a regular loot drop, or so I've been told. Which means it can be tracked as a NPC drop like most other items.

Not that anyone will be farming it after all this time, but still...
