### ISSUE TITLE
Revisit pickpocketing collectibles that are disabled (but still exist in the codebase)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#249]
Allara:
> 3. They’re commented out because either I couldn’t implement them (i.e. the pickpocketing items were too much work) or I decided not to (i.e. the fishing items). I think if you look into the pickpocketing one you’ll find that the list of NPC IDs is absolutely massive, hundreds and hundreds of them, and no user was willing to put that list together. So I left the data I had in case someone decided to do it, but commented it out. If you think the items are useful and can be implemented correctly, feel free to put them in. Or delete them! Probably time to delete them haha.

If there's a way to obtain the NPC IDs from wowhead, adding them should be doable. Otherwise, might as well delete them? No need to keep more cruft around than absolutely functionally necessary.

**Comment by godejord** [comment]
I don't know if the data on Wowhead is inaccurate or not, but currently there are around 30 total NPC IDs linked with the 3 dices from pickpocketing.

[https://www.wowhead.com/item=36862/worn-troll-dice#pick-pocketed-from](https://www.wowhead.com/item=36862/worn-troll-dice#pick-pocketed-from)
[https://www.wowhead.com/item=63269/loaded-gnomish-dice#pick-pocketed-from](https://www.wowhead.com/item=63269/loaded-gnomish-dice#pick-pocketed-from)
[https://www.wowhead.com/item=36863/decahedral-dwarven-dice#pick-pocketed-from](https://www.wowhead.com/item=36863/decahedral-dwarven-dice#pick-pocketed-from)

If these are the only related NPC's, then these items are almost complete in the DB already.

**Comment by SacredDuckwhale** [comment]
Considering the original comment, I'd expect there to be many NPCs that wowhead simply isnt tracking due to having no/little data. We could start with those that it lists and perhaps add missing NPC IDs later if it turns out to be the case?
