### ISSUE TITLE
Set up the Discord server properly

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#250]
Roguinaa (of the Lord of the Reins Discord) has set up a basic Discord server since there've been repeated requests for one. While it's looking decent, it probably could benefit from some restructuring before it's actually "officially" usable.

To that end, they require 2FA, which I've been too busy (i.e., lazy) to set up. And then we probably need different roles, a logo and to integrate the support channels.

**Comment by godejord** [comment]
A proper Discord server could be interesting. It might lower the threshold for people to report minor bugs and missing items, as well as give people a space to show off their collections and stuff.

**Comment by SacredDuckwhale** [comment]
**Update:** The server exists, but it isn't configured fully yet. A logo is currently WIP (the current one is a placeholder) so it's all very much in flux, but this is a permanent invite link anyway in case anyone is curious or has some ideas for improvement: https://discord.gg/2cf5pb62N2

Hopefully within the next few weeks I'll have more time to do something here. Once everything is set up properly, I'll add the link in a "About" tab in the addon's options and see if that works.

**Comment by Duckwhale** [comment]
I decided to simply add two buttons at the top of the main Options window (GitHub and Discord). It's probably not the best way to do this, but certainly the easiest since the main window is difficult to extend.
