### ISSUE TITLE
Add tracking for Gilded Wader

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#278]
[Gilded Wader](https://www.wowhead.com/item=180866/gilded-wader) is a pet that can be dropped from various chests around in the outdoor zones of Shadowlands. Thus far 20 different chest have data for dropping this pet.

**Comment by SacredDuckwhale** [comment]
From wowhead comments:

> Does anybody know if you only have one chance per day of getting this pet regardless of how many chests you open, or if each and every chest you open is a separate chance?

Do the chests have a daily cooldown (loot lockout quest)? If yes, we could add the quest IDs for all relevant objects to the defeat detection. Otherwise, simply extending the "special handling" for opening spells once more should be sufficient.
