### ISSUE TITLE
The 'requires X faction' text calls all items for mounts in options

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#315]
Just saw this randomly while looking through some toys in the options menu. The display text at the top which explains that some items are only available to horde/alliance seems to think all items are mounts. Probably a quick fix, just adding for later.
https://imgur.com/a/spGla14

**Comment by Duckwhale** [comment]
Fixed in 4cae1367b4f2f4378757ecc4f3886b5904a92df0.
