### ISSUE TITLE
Add validation criteria for all fields that have some interaction with each other

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#326]
Some examples:

* Covenant-restricted items require both a flag and a convent ID (used to query Blizzard's API only when actually needed)
* Items obtained from lootable containers expect an ``items`` property for the container(s) you can open to get it
* When waypoint coordinates are set, they should have at least a ``mapID``. When they have x, y values both must exist, etc

There may be others. 

The database schema contains all known fields and if an existing property is unknown, the schema validation will fail.
We can use that as a starting point and simply check each field. in the code (how it is used).

Where there are interactions, they should be checked in the validation logic, by extending the existing API.

Goal: If any of those fields is modified, any field that would also be affected needs to also be modified (or deleted) accordingly to guarantee the addon behaves as expected.

Needs to wait for #320 to be merged first.

**Comment by Duckwhale** [comment]
Am I mistaken or is this now resolved?

@godejord Your PR should cover it all, right?

**Comment by godejord** [comment]
I think I covered all the fields that interact with each other, so this one should be resolved yea 🥳
