### ISSUE TITLE
Add tracking for Gilded Wader (pet)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#330]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/472)

Should be simple enough. The only question is, what's with the requirements? Apparently, wowhead comments aren't quite conclusive.

**Comment by godejord** [comment]
Duplicate of #278.

**Comment by Duckwhale** [comment]
Whoops. I didn't search since the name of this pet seemed unfamiliar.
