### ISSUE TITLE
Tracking for Larion Pouncer might be broken / use the wrong NPC ID

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#336]
Source: [CurseForge](https://www.wowace.com/projects/rarity?comment=2627)
> Hello, I've got an issue with the tracking of Larion Pouncer. The npc id of the npc that is looted seemed correct and localization also should not be an thing in this case. I've disabled the quest id 61634 but this didn't help. So I added 156339 to the npcs and it finally counted. I didn't reactivate the quest id I previously commented out, so I don't know if this matters.

> My line looks like this now "line 578 npcs = {156340, 156339 }," but it wasn't counted twice. So no idea what is wrong with Orstus, but Sotiros works. 

Not sure what's the matter here, maybe it can only looted from one of the NPCs? Perhaps it's "random" which one it is? I have never even been to this location ingame, so I don't know anything about these rares.

**Comment by Duckwhale** [comment]
Looking into this, it appears the rares can only be summoned by Kyrians with the Anima Conductor. That obviously means I can't test it.

Judging from wowhead data, both of the rares seem to be lootable (though maybe not simultaneously?). I'd therefore add both NPC IDs to the list, though this could potentially add two attempts if somehow both end up being lootable.

Will this be a problem? I don't know, maybe someone has killed this rare and could provide some more details? (@godejord  ? :D)

**Comment by Duckwhale** [comment]
From the CurseForge comment:

> Not both of this NPC pair are lootable after defeating them, only Sotiros was glimmering

**Comment by Duckwhale** [comment]
I waited around and two people from the other faction summoned them (independently). Here's my observations:

* The first time (no loot lockout) Sotiros was lootable (the second one didn't die so I can't say if both would've been lootable)
* Rarity did not track an attempt as it doesn't recognize the NPC, as described in the OP
* The second time (loot locked) the other one died, but it was not lootable

The weird thing is that wowhead ONLY shows the pet dropping from the second guy (the one we're currently tracking). I'm not sure what to make of it, but I'd rather avoid adding Sotiros if it can't drop it to avoid people wasting their time killing it.

In fact, wowhead comments suggest you have to be a Kyrian in order to see the drop. I don't know if that's true, but it seems possible. Maybe we should in fact add this restriction to the item, again to avoid people wasting their time farming this on other characters?

**Comment by Duckwhale** [comment]
This time I managed to get both, and only Sotiros was lootable at all. Odd.

**Comment by godejord** [comment]
Killed the two NPCs in question here for the second time in a short while. Cannot recall previous results, but both recent attempts have gone the following; Both NPCs got killed, only Orstus were lootable for me as a Kyrian, attempts tracked as expected. Will try to get some more testing done on this

**Comment by Duckwhale** [comment]
A few random hypotheses regarding the lootable status:

* It's random which one can be looted, but only one per day/lockout
* Kyrians get the "right" one and others (i.e., me) gets the "wrong" one (Sotiros)
* It varies on a day-by-day basis, possibly per character? Seems unlikely...

It should be noted that I only have one character to test this with, and it's not Kyrian. So either of the first two hypotheses might be true... or perhaps I'm completely off with my guesses. I can try to check if I again only get Sotiros while you get Orstus on a Kyrian, but I guess if you have a second character you could try and see if they also get the "wrong" rare on non-Kyrians.

Either way, no evidence to suggest Sotiros should be added so far. wowhead has recorded no drops on it after all this time, so perhaps further investigation is pointless and a waste of time? Up to you if you want to do more testing; we can just close this issue otherwise.

**Comment by godejord** [comment]
So I have been gathering some more data on this to try and find a pattern, and after 5 days this is what I have recorded: 

Day 1
Kyrian kill > Only Orstus lootable

Day 2
Kyrian kill > Both mobs lootable
Necrolord kill > Only Sotiros lootable

Day 3
Kyrian kill > Only Orstus lootable
Necrolord kill > Only Sotiros lootable

Day 4
Kyrian kill > Only Sotiros lootable (WutFace)
Necrolord kill > Only Sotiros lootable

Day 5
Kyrian kill > Only Orstus lootable
Necrolord kill > Only Sotiros lootable


This is in no way any conclusive data, but atleast from my attempts it's looking more like Orstus is only lootable by Kyrians. The others seem to get loot from Sotiros, and this NPC does not have any recorded drop of the pet.

Perhaps this is not a matter of adding the other NPC to the database for tracking, but rather limit the pet to Kyrians only. Sure it won't record any attempts for other covenants like it is now, but if only Kyrians get the loot table, then the pet should be flagged unavailable for other covenants imo,

**Comment by Duckwhale** [comment]
Hmmm... I think that would be in line with our policy of not wasting people's time when we aren't sure about the drop conditions. wowhead comments suggest it only drops for Kyrian, but there's no proper evidence to rely on AFAICT. 

Investigating how exactly the loot is distributed is likely pointless since it seems to be rather... erratic. Random? Who knows.

**Comment by godejord** [comment]
I will open up a PR with the change to flag this item as Kyrian only. I'll leave it up to you if you want to merge it in or leave it as is. Either way I think it's fair to close this issue, as there really isn't any evidence pointing towards Sotiros dropping the pet - nor any faults in tracking an attempt when Orstus is being looted.
