### ISSUE TITLE
Collection items don't show an achievement popup when completed (?)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#339]
Haven't tested this, but while refactoring the GUI I noticed the code references an ``item`` variable that is never passed.

See ``RarityAchievementAlertFrame_SetUp``, and the localized text is ``L["Collection Complete"]``. I think this can't possibly work, but I don't know if I accidentally broke it or if it just hasn't been working for years and no one noticed.

The fix should be simple, though testing collection items might be annoying.

**Comment by godejord** [comment]
Ref #164 :)

**Comment by Duckwhale** [comment]
Ah, look at that! It's me being a doofus again :joy:
