### ISSUE TITLE
Revisit tracking for Bonehoof Tauralus

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#343]
The [Bonehoof Tauralus](https://www.wowhead.com/item=182075/bonehoof-tauralus) mount was added then removed from the DB as it was thought to not be implemented on release. Fast forward half a year and this mount is very much available ingame, allthough the conditions for it to drop is a bit complex.

Still a rare drop it would be nice to track if possible, so should look into this..

**Comment by Duckwhale** [comment]
Agreed! I looked into this a while back, and it seems the mount requires a specific covenant companion to be active?

My initial idea was to see if there's either an aura we could track when the companion is active, or (hacky), determine if the NPC exists and is accompanying the player.

Unfortunately I have no way of testing these things, so I guess someone with the respective covenant requirements (and the NPC unlocked) would need to check if there's a way to track it. Unless someone has a better idea? :disappointed:

**Comment by godejord** [comment]
> Agreed! I looked into this a while back, and it seems the mount requires a specific covenant companion to be active?

Yeah, it seems to require an active companion, or construct as they call it.

> My initial idea was to see if there's either an aura we could track when the companion is active, or (hacky), determine if the NPC exists and is accompanying the player.
> 
> Unfortunately I have no way of testing these things, so I guess someone with the respective covenant requirements (and the NPC unlocked) would need to check if there's a way to track it. Unless someone has a better idea? 😞

I've come far enough into the Necrolord side now that I've created the necessary construct. I'm willing to look into this and see if I have any luck tracking this, but any pointers or tips on where to look would be greatly appreciated.

**Comment by Duckwhale** [comment]
Flying completely blind, my approach would be to try some combination of:

* Checking auras via the ``UnitAura`` API: If there's nothing being displayed it's likely a hidden aura (only exists on the serverside) and can't be queried
* Checking the "talent tree" for the convenant (not sure which API that is, but they ought to have some?)
* Checking the NPC ingame (the relevant bodyguard)
* Anything else that is present if and only if the NPC is accompanying you

**Comment by godejord** [comment]
As someone mentioned in Discord, the companions seem to be trackable by looking at completed hidden quests. Neena (the required compaion for this) has questId 57603. Summoning the companion completes this quest, and removing the companion unflagges the quest again.
Checking if the player is Necrolord and checking if the given quests is completed seems like the way we can safely track an attempt for this mount

**Comment by Duckwhale** [comment]
This is good news! Unfortunately I have no character to test any possible implementation with.

Do you want to take a stab at this? 😃
