### ISSUE TITLE
Add support for collectibles that were introduced in patch 9.1

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#351]
Source: [Discord](https://discord.com/channels/788119147740790854/788145559654760458/859809353233858575)
> Just wondering when support for the 9.1 new shinies will be available in the addon?

I don't have a lot of time right now, but maybe they didn't add a metric ton this time? Either way it would be a little easier adding them now that we have a more structured item database!

Roadmap:

- [x] Mounts: https://github.com/WowRarity/Rarity/issues/354
- [x] Pets: https://github.com/WowRarity/Rarity/issues/355
- [x] Toys: https://github.com/WowRarity/Rarity/issues/356

**Comment by kbuczynski-nashpl** [comment]
### Mounts 
**Hand of Salaranga - https://www.wowhead.com/spell=354355/hand-of-salaranga
Tazavesh Gearglider - https://www.wowhead.com/item=186637/tazavesh-gearglider
Hands of Hrestimorak - https://www.wowhead.com/spell=339957/hand-of-hrestimorak
Mawsworm Charger - https://www.wowhead.com/spell=339956/mawsworn-charger
Soultwisted Deathwalker - https://www.wowhead.com/item=187525/soultwisted-deathwalker
Hand of Nilganihmaht - https://www.wowhead.com/spell=354354/hand-of-nilganihmaht
Hand of Bahmethra - https://www.wowhead.com/spell=352310/links-of-bahmeht
Harvester’s Dredwing - https://www.wowhead.com/spell=332904/harvesters-dredwing
Wild Hunt Legsplitter - https://www.wowhead.com/spell=352441/wild-hunt-legsplitter
Undying Darkhound - https://www.wowhead.com/spell=352742/undying-darkhound
Amber Shardhide - https://www.wowhead.com/item=186647/amber-shardhide
Soaring Razorwing - https://www.wowhead.com/item=186648/soaring-razorwing
Fierce Razorwing - https://www.wowhead.com/spell=354359/fierce-razorwing
Beryl Shardhide - https://www.wowhead.com/spell=347810/beryl-shardhide
Soulbound Gloomcharger - https://www.wowhead.com/spell=354352/soulbound-gloomcharger
Tamed Mauler - https://www.wowhead.com/spell=347536/tamed-mauler
Cartel Master’s Gearglider - https://www.wowhead.com/item=186638/cartel-masters-gearglider
Sanctum Gloomcharger’s Reins- https://www.wowhead.com/item=186656/sanctum-gloomchargers-reins
Vengeance’s Reins - https://www.wowhead.com/item=186642/vengeances-reins
Wandering Arden Doe - https://www.wowhead.com/spell=354362/wandering-arden-doe
Dusklight Razorwing - https://www.wowhead.com/item=186651/dusklight-razorwing
Darkmaul - https://www.wowhead.com/item=186646/darkmaul
Ardenweald Wilderling - https://www.wowhead.com/spell=353856/ardenweald-wilderling
Autumnal Wilderling - https://www.wowhead.com/item=186494/autumnal-wilderling-harness
Winter Wilderling - https://www.wowhead.com/item=186495/winter-wilderling-harness
Summer Wilderling - https://www.wowhead.com/item=186492/summer-wilderling-harness
Elysian Aquilon - https://www.wowhead.com/item=186482/elysian-aquilon
Ascendant’s Aquilon - https://www.wowhead.com/item=186485/ascendants-aquilon
Battle-Hardened Aquilon - https://www.wowhead.com/item=186480/battle-hardened-aquilon
Foresworm Aquilon - https://www.wowhead.com/item=186483/foresworn-aquilon
Maldraxxian Corpsefly - https://www.wowhead.com/item=186487/maldraxxian-corpsefly-harness
Regal Corpsefly - https://www.wowhead.com/item=186488/regal-corpsefly-harness
Battlefield Swarmer - https://www.wowhead.com/item=186490/battlefield-swarmer-harness
Lord of the Corpsefilies - https://www.wowhead.com/item=186489/lord-of-the-corpseflies
Sinfall gravewing - https://www.wowhead.com/item=186476/sinfall-gravewing
Obsidian Gravewing - https://www.wowhead.com/item=186478/obsidian-gravewing
Pale Gravewing - https://www.wowhead.com/item=186477/pale-gravewing
Mastercraft Gravewing - https://www.wowhead.com/item=186479/mastercraft-gravewing**

**Comment by Duckwhale** [comment]
Splitting this into several parts so we can get the mounts out ASAP. Will have to add the rest later and slowly update drop rates etc. as we go.

**Comment by kbuczynski-nashpl** [comment]
### Pets 9.1
```
Damp Skrat - https://www.wowhead.com/npc=179167/damp-skrat
Turquoise Baubleworm - https://www.wowhead.com/npc=179138/turquoise-baubleworm
Fodder - https://www.wowhead.com/npc=179171/fodder
Scavenging Skrat - https://www.wowhead.com/npc=179168/scavenging-skrat
Eye of Allseeing - https://www.wowhead.com/npc=179232/eye-of-allseeing
Irongrasp - https://www.wowhead.com/npc=179222/irongrasp
Silver Purrkin - https://www.wowhead.com/npc=179165/silver-purrkin
Chompy - https://www.wowhead.com/npc=179230/chompy
Gilded Darknight - https://www.wowhead.com/npc=179239/gilded-darknight
Eve of Extermiantion - https://www.wowhead.com/npc=179233/eye-of-extermination
Copperback Etherwyrm - https://www.wowhead.com/npc=179132/copperback-etherwyrm
Amaranthine Stinger - https://www.wowhead.com/npc=179181/amaranthine-stinger
Curious Purrkin - https://www.wowhead.com/npc=179164/curious-purrkin
Squibbles - https://www.wowhead.com/npc=176662/squibbles
Churro - https://www.wowhead.com/npc=176658/churro
RT-3 M15 - https://www.wowhead.com/npc=176657/rt-3-m15
Deathroach - https://www.wowhead.com/npc=179226/deathroach
Invasive Buzzer - https://www.wowhead.com/npc=179180/invasive-buzzer
Gizmo - https://www.wowhead.com/npc=179166/gizmo
Topaz Baubleworm - https://www.wowhead.com/npc=179139/topaz-baubleworm
Gnashtooth - https://www.wowhead.com/npc=179255/gnashtooth
Mawsworn Minion - https://www.wowhead.com/npc=179240/mawsworn-minion
Rook - https://www.wowhead.com/npc=179242/rook
Animite Boordling - https://www.wowhead.com/npc=179131/animite-broodling
Scurrying Mawrat - https://www.wowhead.com/npc=179182/scurrying-mawrat
Lost Limb - https://www.wowhead.com/npc=179183/lost-limb
Domestic Aunian - https://www.wowhead.com/npc=179253/domestic-aunian
Sly - https://www.wowhead.com/npc=179083/sly
Wild Corpsefly - https://www.wowhead.com/npc=179329/wild-corpsefly
Anxious Nibbler - https://www.wowhead.com/npc=179248/anxious-nibbler
Young Garnetgullet - https://www.wowhead.com/npc=179250/young-garnetgullet
Clinging Remains - https://www.wowhead.com/npc=179179/clinging-remains
Devourling - https://www.wowhead.com/npc=179256/devourling
Timless Mechanical Dragonling - https://www.wowhead.com/npc=179125/timeless-mechanical-dragonling
Vile Deathroach - https://www.wowhead.com/npc=179227/vile-deathroach
Eye of Affliction - https://www.wowhead.com/npc=179229/eye-of-affliction
Grip of Terror - https://www.wowhead.com/npc=179219/grip-of-terror
Grappling Gauntlet - https://www.wowhead.com/npc=179220/grappling-gauntlet
Korthia Specimen - https://www.wowhead.com/npc=179251/korthian-specimen
Mosscoated Gromit - https://www.wowhead.com/npc=179252/mosscoated-gromit
Mord’al Eveningstar - https://www.wowhead.com/npc=179241/mordal-eveningstar
Flawless Amethyst Baubleworm - https://www.wowhead.com/npc=178216/flawless-amethyst-baubleworm
Lil’Abom - https://www.wowhead.com/npc=179008/lilabom
Infused Etherwyrm - https://www.wowhead.com/npc=179025/infused-etherwyrm
```

**Comment by kbuczynski-nashpl** [comment]
### Toys 9.1

Forgotten Feather - https://www.wowhead.com/item=187051/forgotten-feather
Ancient Korthain Runes - https://www.wowhead.com/item=187154/ancient-korthian-runes
Offering Kit Maker - https://www.wowhead.com/item=187344/offering-kit-maker
Silver Shardhide Whistle - https://www.wowhead.com/item=187339/silver-shardhide-whistle
Experimental Anima Cell - https://www.wowhead.com/item=186974/experimental-anima-cell
Maw-Ocular Viewfinder - https://www.wowhead.com/item=187420/maw-ocular-viewfinder
Anima-ted Leash - https://www.wowhead.com/item=186973/anima-ted-leash
Bottled Shade Heart - https://www.wowhead.com/item=187139/bottled-shade-heart
Shaded Judgment Stone - https://www.wowhead.com/item=187174/shaded-judgment-stone
Ring of Duplicity - https://www.wowhead.com/item=187140/ring-of-duplicity
Guise of the Changeling - https://www.wowhead.com/item=187155/guise-of-the-changeling
Jailer’s Cage - https://www.wowhead.com/item=187416/jailers-cage
Elusive Pet Treat - https://www.wowhead.com/item=186985/elusive-pet-treat
Shadow Slicing Shortsword - https://www.wowhead.com/item=187159/shadow-slicing-shortsword
Pallid Oracle Bones - https://www.wowhead.com/item=186686/pallid-oracle-bones
Doomwalker Trophy Stand - https://www.wowhead.com/item=186501/doomwalker-trophy-stand
Adamant Vaults Cell - https://www.wowhead.com/item=187417/adamant-vaults-cell
Pallid Bone Flute - https://www.wowhead.com/item=186702/pallid-bone-flute
Vesper of Faith - https://www.wowhead.com/item=187185/vesper-of-faith
Personal Ball and Chain - https://www.wowhead.com/item=187113/personal-ball-and-chain
Bonestorm Top - https://www.wowhead.com/item=183901/bonestorm-top
Box of Rattling Chains - https://www.wowhead.com/item=187075/box-of-rattling-chains
Vesper of Harmony - https://www.wowhead.com/item=187176/vesper-of-harmony
Vesper of Clarity - https://www.wowhead.com/item=187184/vesper-of-clarity

**Comment by Duckwhale** [comment]
Closing this as resolved, as the brunt of the new items have been added. The remaining ones will be added one by one as more data becomes available; they already have separate issues.
