### ISSUE TITLE
Add tracking for Box of Rattling Chains

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#358]
https://www.wowhead.com/item=187075/box-of-rattling-chains 
Need to detect which Torghast layer players are on. Only drops on layer 9-12

**Comment by nickbayley** [comment]
Not sure if there is a better way, but [`GetInstanceInfo()`](https://wowpedia.fandom.com/wiki/API_GetInstanceInfo) exposes [`LfgDungeonID`](https://wowpedia.fandom.com/wiki/LfgDungeonID). For example `2197` is "Torghast: Skoldus Hall (Layer 9)".

**Comment by Duckwhale** [comment]
Any progress on this (since you self-assigned the issue)? If not, we could ask people on Discord if someone is still running Torghast?

**Comment by godejord** [comment]
> Any progress on this (since you self-assigned the issue)? If not, we could ask people on Discord if someone is still running Torghast?

Unfortunately haven't gotten around to look into this. Will release the assignation and hope someone else have time to pursue it

**Comment by Duckwhale** [comment]
No worries! I'll see if can hack together something that might just work, and then it's up to others to test it (I guess) 🚀

**Comment by cyriun** [comment]
does this drop up to layer 16 now? seeing comments saying it dropped from layer 16

**Comment by Duckwhale** [comment]
I have no info beyond those wowhead comments, but it looks like it does drop from higher layers. Perhaps at the time this issue was created the maximum layer was lower, and it now includes all those above that? (would have to dig up patch notes to confirm)
