### ISSUE TITLE
Add tracking for Shaded Judgment Stone

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#359]
https://www.wowhead.com/item=187174/shaded-judgment-stone
Could be locked behind Tier 4 in Korthia(?) Need to wait until there is more available data on the source

**Comment by godejord** [comment]
16 days later, still no data on the source of this item. This may not have been added to the game..

**Comment by Duckwhale** [comment]
In before you need to come prepared with a special convenant companion, talent build, ride the new shop mount and ``/mountspecial`` three times while facing towards the sun in order to make it drop.

Or maybe it's just bugged :confused:

**Comment by godejord** [comment]
Eventually this item got hotfixed into the game and started dropping. The exact data on which creatures and at what percentage it drops is still rather up in the air though. Could probably be added with the few confirmed sources there are along with a common drop rate

**Comment by Duckwhale** [comment]
Sounds good to me!
