### ISSUE TITLE
Add tracking for Rarity (nice)

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#365]
https://www.wowhead.com/item=186540/rarity#battle-pet
Zone: Tazavesh, the Veiled Market

**Comment by Duckwhale** [comment]
It's not a rare drop, but rather sold by a vendor. Disappointing :confused:

**Comment by godejord** [comment]
> It's not a rare drop, but rather sold by a vendor. Not much of a rarity now, is it? Disappointing 😕

Oh really. Daww.. that's not rare at all then Q.Q
