### ISSUE TITLE
Looting Bonestorm Top isn't being detected (?)

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#369]
From Discord
>Just got my first kill on Darklord Taraxis in the Beastwarrens and was lucky enough to get the toy! Unfortunately looks like detection for me receiving it didn't trigger for some reason. I'm using r709-release-2.
>
>[Photo proof](https://cdn.discordapp.com/attachments/788119314909626388/860756446598004736/unknown.png)

**Comment by Duckwhale** [comment]
Can we even reproduce this? The achievement toast window is definitely working, I tested it after the GUI refactoring.

The loot detection might not always work 100%, but we haven't touched it in ages so I don't see why it would suddenly stop working.

**Comment by godejord** [comment]
I don't see why it wouldn't work either.. Can also confirm that the toast in general works just fine on other items. I've been trying this particular toy several times, just haven't had any drops yet.

**Comment by Duckwhale** [comment]
It's been posted on [Discord](https://discord.com/channels/788119147740790854/788119314909626388/862540025401049088) that the problem might also affect at least one other item:

> Here's a bit more evidence for detection sometimes not working. Another toy obtained on the first attempt from Observer Yorik in the rift on Korthia. This has only happened to me for the Darklord Taraxis toy and now this one. I've obtained a couple pets (one on a first attempt in Sanctum last night) and one mount and detection/screenshot taking has worked for those. Using r709-release-5.

Unfortunately, without more information I don't know if it can be reproduced. "Sometimes" is generally not sounding like an actionable issue.

**Comment by godejord** [comment]
Can confirm that I have not been able to reproduce this. I did end up getting this toy after several days worth of attempts, and the detection triggered just fine as expected for me. [Here ](https://imgur.com/a/HewoQQA)is a proof

**Comment by Duckwhale** [comment]
I guess we can only see if there are other reports of this happening in the future. I'll leave this open, for now, but we might as well close it if no one else encounters this problem.

**Comment by godejord** [comment]
There hasn't been any more reports of this particular issue. On the contrary, I have seen multiple screenshots posted on various Discord channels from people who have looted this item and showed off their Rarity attempts for it. Closing this issue as it seems like a dead end
