### ISSUE TITLE
Attempts for Summer Wilderling aren't being tracked since the rare doesn't "die"

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#378]
Source: [Discord](https://discord.com/channels/788119147740790854/788119314909626388/862105784355913728)
> Completed the Escaped Wilderling event and it seems like tracking for the Summer Wilderling did not trigger. This rare is a bit odd as you never actually kill it you just weaken it and then ride it around in the air trying to tame it. If you are successful you receive loot.

**Comment by godejord** [comment]
There are some claims that you get a sort of [lootbox](https://ptr.wowhead.com/item=187278/talon-pierced-mawsworn-lockbox) after completing this event. But no confirmed source yet on this box actually containing the mount - also no knowledge if this box is a guaranteed reward every time you complete the event

**Comment by Duckwhale** [comment]
From the wowhead comments and Blizzard's source being the Escaped Wilderling, I'd assume the mount can be obtained from the box. It currently tracks the NPC itself, but if that never dies it won't trigger.

Whether the box is guaranteed shouldn't really matter if we just add the mount as a container drop (``USE`` method). I'll do this quickly as it's a trivial change.

**Comment by Duckwhale** [comment]
Not actually resolved, as it seems like the mount is a quest reward, but the quest item drops alongside the container.

**Comment by Duckwhale** [comment]
We need a way to track that the rare event is happening/just happened. Maybe the unit's state changes? Can probably try to run ``/etrace`` while doing the event, but have to mute all the spam/combat stuff beforehand. Not sure how difficult it is to even find the rare alive, might be very difficult to debug properly.

**Comment by Duckwhale** [comment]
Here's my findings after checking the event ingame...

When mounting the thing: 

![image](https://user-images.githubusercontent.com/16489133/125066436-4b2de980-e0b3-11eb-9c44-0722d300e545.png)

When looting the box:

![image](https://user-images.githubusercontent.com/16489133/125066514-5da82300-e0b3-11eb-85dd-70fd9f3cf91d.png)

Then the vehicle is exited:

![image](https://user-images.githubusercontent.com/16489133/125066552-68fb4e80-e0b3-11eb-9101-bdece781c60f.png)

And finally, the quests that were flagged as completed:

![image](https://user-images.githubusercontent.com/16489133/125066590-757fa700-e0b3-11eb-9cbc-8eb591b02a86.png)

**Comment by Duckwhale** [comment]
It looks as though the ONLY event would be ``SHOW_LOOT_TOAST``, i.e. we could track when the lockbox is awarded. However, if the quest item is also looted there's no telling whether the attempt would be registered before the item or afterwards.

Another issue is that the item link is localized. I'm not sure if we would have to account for that or if the item ID is sufficient.

**Comment by Duckwhale** [comment]
Relevant properties: https://wowpedia.fandom.com/wiki/SHOW_LOOT_TOAST

I'm currently investigating whether we can detect the item across different client locales, without having to translate the item's name. If yes, I may have a solution. If no, it could still work if we just add this phrase manually for all locales (from wowhead's item page).

Will test after the reset as I'm currently locked out.
