### ISSUE TITLE
Add "Undefeated"/"Defeated" for Chain of Bahmethra

### ISSUE THREAD

**Issue by asleire** [WowRarity/Rarity#384]
[Chain of Bahmethra](https://www.wowhead.com/item=185973/chain-of-bahmethra#comments) can be looted from [Tormentor's Cache](https://www.wowhead.com/item=185972/tormentors-cache#comments) which is only obtainable once per week through the new Torments event

According to a Wowhead comment, the quest ID to check is 63854

It would be nice if the rarity UI could show whether the event has been completed the current week😃

**Comment by Duckwhale** [comment]
Thanks! Fixed via fe7e64d.
