### ISSUE TITLE
Necroray Egg isn't tracked properly from Calling turn-ins (?)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#393]
Source: [Curse](https://www.wowace.com/projects/30801?comment=2640)
> Necroray egg from the calling turn ins are not tracking the attempts

No idea. This is an old comment I found in my inbox, but somehow it's not visible on Curse (spam filtered?)

**Comment by nickbayley** [comment]
I'll try to remember to check this the next time a Maldraxxus calling is up. I have definitely had attempts tracked since 9.1 as I still have never looted a bloody egg!

**Comment by godejord** [comment]
I've done almost every single Maldraxxus calling since like forever. I have never had a single attempt not tracked, so this is likely not an issue

**Comment by nickbayley** [comment]
There is a Maldraxxus calling up today. Just finished it and it successfully tracked my attempt (still no egg though!).

**Comment by Duckwhale** [comment]
Seems like fake news then. Will close as invalid until such a time that someone else reports the same issue.
