### ISSUE TITLE
Error on login re farm holiday items reminder

### ISSUE THREAD

**Issue by Tequima** [WowRarity/Rarity#424]
As of today, getting this error every time I log into a character (note that I have all the Brewfest mounts, toys, pets and have yet to run the dungeon this year due to low i:evel of loot; the interface settings loads up fine):

6x AceLocale-3.0-6: Rarity: Missing entry for 'When on, Rarity will remind you to go farm holiday items you're missing if the holiday is active and the item is set as Undefeated. (This only works for items that originate from holiday dungeons or daily quests.) The reminder occurs each time you log in or reload your UI, and stops for the day once you defeat the holiday dungeon or complete the	quest.'
[string "@Rarity_Options\Options-Options.lua"]:2591: in function `CreateGroup'
[string "@Rarity_Options\Options-Options.lua"]:1570: in function `PrepareOptions'
[string "@Rarity_Options\Options-Options.lua"]:107: in function `Options_DoEnable'
[string "@Rarity_Options\Options-Options.lua"]:86: in function <Rarity_Options\Options.lua:85>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML\UIParent.lua"]:509: in function `UIParentLoadAddOn'
[string "@Rarity\Core\Collections-Collections.lua"]:63: in function `ScanToys'
[string "@Rarity\Core\Collections-Collections.lua"]:307: in function `ScanExistingItems'
[string "@Rarity\Core.lua"]:175: in function `DoEnable'
[string "@Rarity\Core.lua"]:151: in function <Rarity\Core.lua:150>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:527: in function `EnableAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:630: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by alexnaumovich** [comment]
Getting the same error since last update.

**Comment by Duckwhale** [comment]
Thanks, looks like there was an accidental tab character (instead of space). It appears to have slipped in many years ago, still in the SVN code (I never even noticed), and a recent whitespace adjustment in the localization phrases brought it to light.

Very peculiar, but it should be fixed in a1e63bb (``r711-release-2``).
