### ISSUE TITLE
Fix backdrop-related UI errors introduced by patch 9.1.5

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#430]
Source: [Discord} (and #429 )

> Seems Rarity has the Backdrop issue from 9.1.5 i keep seeing on other addons too. Could be Titan Panels problem though 
4x ...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0-48.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Rarity\Libs\LibQTip-1.0\LibQTip-1.0-48.lua"]:543: in function <...rfaceRarity\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Rarity\Libs\LibQTip-1.0\LibQTip-1.0-48.lua"]:132: in function Acquire'
[string "@SavedInstances\Core\Core.lua"]:3430: in function ShowTooltip'
[string "@SavedInstances\Core\Core.lua"]:2531: in function <SavedInstances\Core\Core.lua:2529>
[string "@Titan\LDBToTitan.lua"]:343: in function <Titan\LDBToTitan.lua:302>

---

I was unable to find any official information on the changes. Some details were posted [here](https://us.forums.blizzard.com/en/wow/t/backdroptemplate-issues/1125674/7) but I'm not sure where they got them.

**Comment by Duckwhale** [comment]
Since this error originates in LibQTip, we will have to wait for an update to it. Alternatively, we could fork and embed the library, which I don't think is a good idea due to the "All rights reserved" license.

Come to think of it, that problem also applies if it's embedded via CurseForge.... so no idea what to make of it.

**Comment by Duckwhale** [comment]
Some more details here: https://www.curseforge.com/wow/addons/libqtip-1-0/issues/49

**Comment by Dawawe** [comment]
There is an alpha version of QTip out that fixes the issue. Just replaced the old folder with the new.

https://www.curseforge.com/wow/addons/libqtip-1-0/files

**Comment by Duckwhale** [comment]
Should be fixed in r712.
