### ISSUE TITLE
Add tracking for the New Covenant Toys from Calling Boxes in Patch 9.1.5

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#432]
Patch 9.1.5 added four new Covenant-themed toys. These can be obtained from Covenant calling boxes.
[https://www.wowhead.com/news/new-covenant-toys-from-calling-boxes-in-patch-9-1-5-324045](https://www.wowhead.com/news/new-covenant-toys-from-calling-boxes-in-patch-9-1-5-324045)

Drop rate unclear. Should add some tracking for these toys

**Comment by Duckwhale** [comment]
I assume they're obtained via opening the boxes (containers), so it wouldn't require a new feature since Rarity already can track them in theory :)
