### ISSUE TITLE
Add tracking for new mount and toy off Doomwalker anniversary event

### ISSUE THREAD

**Issue by nzall** [WowRarity/Rarity#433]
Illidari Doomhawk is a new mount off Doomwalker in Tanaris for the Anniversary event. I'm not sure about the drop rate or the reset rate, but the drop rate seems to be about 1% based on Wowhead comments. Reset is either daily or weekly.

Doomwalker also drops a toy called Doomwalker Trophy Stand. Not sure about that drop rate either.

**Comment by Duckwhale** [comment]
Thanks, I've already read about this yesterday (in the Discord) but I didn't have time to look into tracking it by default. I will see what I can do to add this shortly.

In the meantime: There's an import string posted in the Discord, which has been reported to work:

> AzOjAf8CalW0TVXNlnJTBX6poNsUO5X2wm6U/SrKT1EZRsU4lTRURTVYJRqO6KAoHaPqnCq1kEpLVWGxguUSPSWWSeW5yEQEU5GarGg66apKuCxcV2ijCnWY0mYJXouqaQidVymfReG7SnUa1TcJjVaV8SrSSal6jOSaCrmnSlaKorUq4rek4UFDuIZJoLEdaEickrVUuJBERmv9xP6dQ7xCmk2aVQ1DasI6kFapvFtTWmsCQqjV3G3LRwlRbgLrIYykEmisx/q/WCS+oRDqs4wKrHcciFUNQ2rCekgwO7SYcCF6IwNykLtYGmJCvzohbk4Ewg1ZS8X/AuEapp9Yf/2J/wEbUqgjmxggzJqA9K3xaUt+dkmo1Xz2nocEs0OLLGN1ZFSYYJrgQjhLahkVBF4ocGpsyiOBxjpwoZCvNj7t7RGGsxklXMi0Ggk0tnM6770/Ag1RbgLrIVY1DKkJ66FQKBSSeAazOpYBeRz33TmB+Mw9M51lmtEz6vAk+3pBhpG3iS36Dgr/Ag==

Please note that attempts won't be carried over if you use this and later Rarity tracks attempts natively, as both would be in a different group.

**Comment by Duckwhale** [comment]
Should be tracked as of 76a37d8203560ab99291211dba14c0cd97014ef5.
