### ISSUE TITLE
Add new collectibles for patch 9.2

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#462]
Not much to add this time around...

## Mounts

Likely relevant:

- [x] https://ptr.wowhead.com/item=190765/iskas-mawrat-leash#comments
- [x] https://ptr.wowhead.com/item=190766/spectral-mawrats-tail
- [x] https://ptr.wowhead.com/item=188700/sturdy-silver-mawrat-harness
- [x] https://www.wowhead.com/item=187676/deepstar-polyp

Source: [https://ptr.wowhead.com/items/miscellaneous/mounts?filter=82;2;90200](https://ptr.wowhead.com/items/miscellaneous/mounts?filter=82;2;90200)

Most of the mounts are listed as crafting mounts ("Progenitor Synthesis"); I skipped all them. Raid mounts might be guaranteed, so no idea if they'll need to be added yet.

## Pets

Likely relevant:

- [x] https://ptr.wowhead.com/item=187735/geordy#teaches-ability

Seems there isn't anything here, really, but maybe I misread the wowhead info.

Source: [https://ptr.wowhead.com/battle-pets?filter=3;2;90200](https://ptr.wowhead.com/battle-pets?filter=3;2;90200)

## Toys

Likely relevant:

- [x] https://ptr.wowhead.com/item=190177/sphere-of-enlightened-cogitation#comments
- [x] https://ptr.wowhead.com/item=190238/xyraths-booby-trapped-cache
- [x] https://ptr.wowhead.com/item=190734/makariss-satchel-of-mines

TBD:

* https://ptr.wowhead.com/item=190196/enlightened-hearthstone

Source: [https://ptr.wowhead.com/items/miscellaneous/other?filter=216:82;1:2;0:90200](https://ptr.wowhead.com/items/miscellaneous/other?filter=216:82;1:2;0:90200)

## Meta

- [x] Update TOC version for 9.2
- [ ] Update localization phrases on WowAce

**Comment by Duckwhale** [comment]
Not sure about the Torghast one, but it's probably best to get the changes merged ASAP and add to it later.

**Comment by lgkern** [comment]
https://ptr.wowhead.com/item=188700/sturdy-silver-mawrat-harness

Is from the last boss of the run or the boss from Adamant Vaults only.

**Comment by Duckwhale** [comment]
Thanks! I had originally considered the polyp, but since wowhead comments claimed it was a guaranteed drop I then removed it from the list. There seems to be conflicting information and I don't know what to make of it.

If it is indeed a rare drop it could be added, but there's no way to differentiate between attempts with high vs those with low chance. I suppose the best solution would be to set it to a low drop chance, and add a comment that the chance is much higher if you're the one who summoned it?

**Comment by Duckwhale** [comment]
As for the mawrat, wowhead currently lists only one NPC (https://www.wowhead.com/npc=171422/arch-suppressor-laguas). If it can also drop from other bosses I'd need to know which NPCs to add.

Perhaps @godejord knows which of the other NPC IDs should be added? I don't know much about Torghast, unfortunately.

**Comment by Duckwhale** [comment]
I'll publish this in its current state, as it should be useful enough and there's no point in making people wait even longer. If there are some issues, we can address them as they come up :)

**Comment by lgkern** [comment]
> As for the mawrat, wowhead currently lists only one NPC (https://www.wowhead.com/npc=171422/arch-suppressor-laguas). If it can also drop from other bosses I'd need to know which NPCs to add.
> 
> Perhaps @godejord knows which of the other NPC IDs should be added? I don't know much about Torghast, unfortunately.

You can add the bosses listed here: https://www.wowhead.com/guides/adamant-vaults-torghast-traps-bosses-rewards-strategy and the three bosses listed here https://www.wowhead.com/guides/adamant-vaults-torghast-traps-bosses-rewards-strategy#bosses-in-the-adamant-vaults

**Comment by lgkern** [comment]
> Thanks! I had originally considered the polyp, but since wowhead comments claimed it was a guaranteed drop I then removed it from the list. There seems to be conflicting information and I don't know what to make of it.
> 
> If it is indeed a rare drop it could be added, but there's no way to differentiate between attempts with high vs those with low chance. I suppose the best solution would be to set it to a low drop chance, and add a comment that the chance is much higher if you're the one who summoned it?
When you summon it with the rare lure, the drop rate is 100%,so probably worth just adding the low chance (which seems to be really low from observations) 

Watched around 1000 people killing it and saw only 3 drops that weren't increased drop rate. So probably 1:200 if not lower,but early to tell.

**Comment by Duckwhale** [comment]
Strange Goop added in af4da7b, and more NPCs for the mawrat in a58d435. I'm currently investigating a bug with the chest detection, but I'll publish a new release after that is done (or when I run out of time to look into it) so those changes should be live soon-ish :)

**Comment by lgkern** [comment]
@Duckwhale You can copy the list of NPCs for Gilded Darknight and Maw Stalker for the mount, that should cover all Torghast bosses.

**Comment by Duckwhale** [comment]
Thanks, I added three missing NPC IDs in 614195c :)
