### ISSUE TITLE
Holiday reminders aren't displayed after logging in, until the main window is opened (?)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#492]
Source: [Discord](https://discord.com/channels/788119147740790854/788119314909626388/1034115793572614154)
> Mine holiday reminder only shows me when i mouse over the mini rarity icon, then the text shows up in the middle of the screen, it dosent show when i log in on new character only when i mouse over it. How do i fix it?

**Comment by godejord** [comment]
Duplicate of #312
