### ISSUE TITLE
Attempt to register unknown event "CURSOR_UPDATE"

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#493]
Source: [Discord](https://discord.com/channels/788119147740790854/788119314909626388/1034772923220758618)
> I get a lua error, but I dont know how to tell if it is related to Rarity or not. Rarity works, i just have to close the error when it pops up. Is it maybe a shared library that has some issue and that is why rarity is named with other addons (that work)

I guess it was simply moved to the ``C_Cursor`` namespace, but that remains yet to be verified.

**Comment by fraerie** [comment]
Getting the same issue


15x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "CURSOR_UPDATE"
[string "=[C]"]: in function `RegisterEvent'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceEvent/AceEvent-3.0-4.lua"]:33: in function `OnUsed'
[string "@Interface/AddOns/ArkInventory/Libs/CallBackHandler/CallbackHandler-1.0-7.lua"]:142: in function `RegisterEvent'
[string "@Interface/AddOns/Rarity/Core/EventHandlers.lua"]:68: in function `Register'
[string "@Interface/AddOns/Rarity/Core.lua"]:189: in function `DoEnable'
[string "@Interface/AddOns/Rarity/Core.lua"]:151: in function <Interface/AddOns/Rarity/Core.lua:150>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11011: in function `LoadAddOn'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:11027: in function `BlizzardAPIHook'
[string "@Interface/AddOns/ArkInventory/Core/ArkInventory.lua"]:2881: in function <Interface/AddOns/ArkInventory/Core/ArkInventory.lua:2850>
[string "=[C]"]: ?
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:66: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/ArkInventory/Externals/Ace3/AceAddon/AceAddon-3.0-13.lua"]:626: in function <...rkInventory/Externals/Ace3/AceAddon/AceAddon-3.0.lua:611>

**Comment by Duckwhale** [comment]
This likely also blocks kill statistics from being synced, going by some info posted on Discord.

**Comment by Duckwhale** [comment]
The event was removed completely, but I can't find any information about the reasoning/possible replacements (of course...).

Initial testing suggests [CURSOR_CHANGED](https://wowpedia.fandom.com/wiki/CURSOR_CHANGED) can be used to detect fishing nodes instead, though it doesn't seem to be quite ideal.

**Comment by Duckwhale** [comment]
World objects are apparently no longer being detected, see #498 :(

I don't think there's a different fix for this issue that also resolves the latter, since there appears to be only one relevant cursor event left.
