### ISSUE TITLE
Add new World Event collectibles for BFA

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#50]
Roadmap:
- [ ] Research: How are they obtained?
- [ ] Research: Do they need defeat detection?

**Comment by SacredDuckwhale** [comment]
Possibly related: #67

**Comment by godejord** [comment]
I've looked over the [ingame events](https://www.wowhead.com/events/holidays). Not just for BfA, but in general, and here is my conclusion:
- Noblegarden (0 items in database, 0 rare items, 0 items missing)
- Children's Week (0 items in database, 0 rare items, 0 items missing)
- Lunar Festival (0 items in database, 0 rare items, 0 items missing)
- Midsummer Fire Festival (1 item in database, 1 rare item, 0 items missing)
- Love is in the Air (3 items in database, 3 rare items, 0 items missing)
- Hallow's End (3 items in database, 3 rare items, 0 items missing)
- Brewfest (2 items in database, 2 rare items, 0 items missing)
- Pirates' Day (0 items in database, 0 rare items, 0 items missing) **NB: One 90% drop rate item not added.**
- Pilgrim's Bounty (2 items in database, 2 rare items, 0 items missing)
- Feast of Winter Veil (34 items in database, 34 rare items, 0 items missing)
- Day of the Dead (0 items in database, 0 rare items, 0 items missing)
- Harvest Festival (0 items in database, 0 rare items, 0 items missing)
- WoW's Anniversary (0 items in database, 0 rare items, 0 items missing)

Total 0 items missing.

**Comment by Duckwhale** [comment]
Hmm. I thought they converted some items/added new ones, but thanks for checking!
