### ISSUE TITLE
Add Dragonflight mounts to the database

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#515]
Here is a list of new mounts that should be looked into and potentially added. I have gone over the full list and filtered out irrelevant items.
Note that some of these are still missing accurate drop rates.

- [ ] [Verdant Skitterfly](https://www.wowhead.com/item=192764/verdant-skitterfly) Prerequisite: Renown 25 with Dragonscale Expedition. Source is available before getting the required renown, so needs to take this into account
- [x] [Reins of the Liberated Slyvern](https://www.wowhead.com/item=201440/reins-of-the-liberated-slyvern) (#521)
- [x] [Plainswalker Bearer](https://www.wowhead.com/item=192791/plainswalker-bearer) (#521)

**Comment by Duckwhale** [comment]
Looking into the Skitterfly mount, it seems to require looting [yet another object from the ground](https://www.wowhead.com/object=376587/expedition-scouts-pack).

As for the renown check, I think this might work: 

* [C_MajorFactions.GetMajorFactionIDs](https://wowpedia.fandom.com/wiki/API_C_MajorFactions.GetMajorFactionIDs) to find the right ID
* [C_MajorFactions.GetCurrentRenownLevel](https://wowpedia.fandom.com/wiki/API_C_MajorFactions.GetCurrentRenownLevel) to check the renown level

So far that's completely untested (I don't even have DF), but it should be easy enough to manually verify ingame.

**Comment by cyriun** [comment]
excluding renown, is the verdant skitterfly similar to the spectral mawrat's tail from shadowlands?

**Comment by Duckwhale** [comment]
> excluding renown, is the verdant skitterfly similar to the spectral mawrat's tail from shadowlands?

I can't say for sure, but if it's an object lootable from a container on the ground then yes - it should use the same method.

**Comment by cyriun** [comment]
used the same method and it works for every expedition scout pack looted regardless of renown, just got to add the renown check now.
