### ISSUE TITLE
Add Dragonflight pets to the database

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#516]
Here is a list of new pets that should be looked into and potentially added. I have gone over the full list and filtered out irrelevant items.

All of these are listed as world drops from their respective elemental storm invasion, but no further information beyond that.
- [x] [Echo of the Cave](https://www.wowhead.com/item=200183/echo-of-the-cave)
- [x] [Echo of the Depths](https://www.wowhead.com/item=200260/echo-of-the-depths)
- [x] [Echo of the Heights](https://www.wowhead.com/item=200263/echo-of-the-heights)
- [x] [Echo of the Inferno](https://www.wowhead.com/item=200255/echo-of-the-inferno)

Edit:
Two more added to the list
- [x] [Bakar Companion](https://www.wowhead.com/item=200290/bakar-companion)
- [x] [Ohuna Companion](https://www.wowhead.com/item=200276/ohuna-companion)

**Comment by cyriun** [comment]
how would you go about adding the npc ids to those pets? add the ones above 1% drop or all of them?

**Comment by cyriun** [comment]
gotcha, can take a look at it in game if you havent yet.

**Comment by Duckwhale** [comment]
Huh, Just saw this old issue... Seems Rarity doesn't currently check for the event being active at all. I'll open a new issue for that, since the items have already been added, so I'd consider it a bug that attempts are always added (even when no event is active).
