### ISSUE TITLE
World boss mount drop rates need to be updated

### ISSUE THREAD

**Issue by DominicABrooks** [WowRarity/Rarity#527]
Source: [Blue Post](https://us.forums.blizzard.com/en/wow/en/wow/t/wow-hotfixes-updated-november-30/1403968/15)

> The drop chances for Son of Galleon's Saddle, Reins of the Heavenly Onyx Cloud Serpent, Reins of the Cobalt Primordial Direhorn, Reins of the Thundering Cobalt Cloud Serpent, and Solar Spirehawk have been greatly increased.

**Comment by Duckwhale** [comment]
Is there any consensus on what the new drop rates should be?

**Comment by Duckwhale** [comment]
Sounds like 1% might be a reasonable estimate. Not sure about Rukhmar, seems like a statistical outlier due to the small sample.
