### ISSUE TITLE
Missing item sources for "Porcupette" battle pet

### ISSUE THREAD

**Issue by Taizunz** [WowRarity/Rarity#535]
The following two bags can also contain that specific battle pet:
https://www.wowhead.com/item=142447/torn-sack-of-pet-supplies
https://www.wowhead.com/item=151638/leprous-sack-of-pet-supplies

**Comment by Taizunz** [comment]
And this one as well:
https://www.wowhead.com/item=184866/grummlepouch

**Comment by Duckwhale** [comment]
Thanks! Looks like wowhead doesn't have any drops for those bags, which is why they don't show up on the Porcupette page.

**Comment by Duckwhale** [comment]
Actually, come to think of it this may be because they use pushed loot (loot toasts) instead of regular containers? (IIRC)

I'll update the database anyway, but if the detection isn't working that might warrant looking into on a separate occasion.
