### ISSUE TITLE
Add Dragonflight 10.0.7 pets to the database

### ISSUE THREAD

**Issue by cyriun** [WowRarity/Rarity#545]
These pets seem to drop from most, if not all chests located inside the zskera vault

- [x] [Bunbo](https://www.wowhead.com/item=193363/bunbo#contained-in-object)
- [x] [Berylmane](https://www.wowhead.com/item=193854/berylmane#contained-in-object)
- [x] [Brightfeather](https://www.wowhead.com/item=193835/brightfeather#contained-in-object)

**Comment by Duckwhale** [comment]
Also this, presumably:

- [ ] https://www.wowhead.com/item=204079/gilded-mechafrog

**Comment by cyriun** [comment]
i might try complete this next but wondering if theres a quicker way to do this? Something like adding all the chests to one table and go from there

**Comment by Duckwhale** [comment]
> i might try complete this next but wondering if theres a quicker way to do this? Something like adding all the chests to one table and go from there

Yeah, probably. Feel free to open a draft PR if you'd like to discuss the code (or ideas for implementing the detection more easily).

**Comment by cyriun** [comment]
working on something atm but i doubt its anything better then whats already done, doesnt seem so anyways

**Comment by Duckwhale** [comment]
This is where I should've mentioned Emmah, I suppose... Anyway, it's now complete! Thanks again.

**Comment by cyriun** [comment]
> This is where I should've mentioned Emmah, I suppose... Anyway, it's now complete! Thanks again.

yup, i believe every toy or pet obtained inside the vaults has been added
