### ISSUE TITLE
Add Dragonflight 10.0.7 toys into DB

### ISSUE THREAD

**Issue by cyriun** [WowRarity/Rarity#546]
So far i have only seen 1 toy drop from the zskera vault, it seems to drop from all the chests in the vault

- [x] [Obsidian Battle Horn](https://www.wowhead.com/item=204687/obsidian-battle-horn)

**Comment by Duckwhale** [comment]
Are these relevant?

* https://www.wowhead.com/item=204257/holoviewer-the-lady-of-dreams
* https://www.wowhead.com/item=204262/holoviewer-the-timeless-one
* https://www.wowhead.com/item=204256/holoviewer-the-scarlet-queen

The comments on wowhead aren't quite clear about whether they're random drops, and the drop rate also seems fairly high.

**Comment by cyriun** [comment]
one seems to be over 50% and the other 2 around 20% from looking at this page
https://www.wowhead.com/object=388712/opera-chest

**Comment by Duckwhale** [comment]
Yes, that's pretty much what I was referring to with "comments aren't clear". It seems that the drop of 2/3 items isn't guaranteed.

**Comment by cyriun** [comment]
> Are these relevant?
> 
> * https://www.wowhead.com/item=204257/holoviewer-the-lady-of-dreams
> * https://www.wowhead.com/item=204262/holoviewer-the-timeless-one
> * https://www.wowhead.com/item=204256/holoviewer-the-scarlet-queen
> 
> The comments on wowhead aren't quite clear about whether they're random drops, and the drop rate also seems fairly high.

also im assuming this just works like any other collectible from a chest. It's a bit annoying to test but when i tested it once i got the last toy i needed and it gave me "you found this toy on your first attempt" but not an attempt for the other toy since i set the toys i already had to repeatable in the addon. I'll try test it again even though its a pain

**Comment by Duckwhale** [comment]
It might be easier to test with a different chest object, i.e,, one that's easily accessible. Changing the object name is trivial, after all.

Realistically, the entire mouseover logic should be streamlined and turned into a proper method of detection, but I lack time :(

**Comment by cyriun** [comment]
ok found the issue, had self.db.profile.groups.items[name] set to .toys instead of .items haha.

**Comment by Duckwhale** [comment]
I believe this is now resolved, after Emmah has been added in #553 🥳
