### ISSUE TITLE
Core.lua:200: attempt to call global 'RequestArtifactCompletionHistory' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [WowRarity/Rarity#557]
Receiving the following error when I log into the game after the update to 10.1.5. Thanks
Version: r719-alpha-4

1x Rarity/Core.lua:200: attempt to call global 'RequestArtifactCompletionHistory' (a nil value)
[string "@Rarity/Core.lua"]:200: in function `DoEnable'
[string "@Rarity/Core.lua"]:150: in function <Rarity/Core.lua:149>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:175: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:168: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:163: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:154: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:150>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:118: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
self = <table> {
 UpdateSessionAttempts = <function> defined @Rarity/Core/GUI.lua:161
 lockouts_detailed = <table> {
 }
 OnMouseOver = <function> defined @Rarity/Core/EventHandlers.lua:621
 ProcessCollectionItemSingle = <function> defined @Rarity/Core/EventHandlers.lua:1022
 ReleaseBar = <function> defined @Rarity/Libs/LibBars-1.0/LibBars-1.0.lua:288
 modules = <table> {
 }
 CancelTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:147
 string_methods = <table> {
 }
 OnChatCommand = <function> defined @Rarity/Core/EventHandlers.lua:661
 advancedSettings = <table> {
 }
 Testing = <table> {
 }
 GetInventoryItemCount = <function> defined @Rarity/Core/EventHandlers.lua:1016
 OnSpellcastFailed = <function> defined @Rarity/Core/EventHandlers.lua:876
 ProfileStart = <function> defined @Rarity/Core/Debugging.lua:25
 ScanArchFragments = <function> defined @Rarity/Core/Collections.lua:311
 AuctionDB = <table> {
 }
 ProcessCollectionItemAggregate = <function> defined @Rarity/Core/EventHandlers.lua:1048
 bagitems = <table> {
 }
 advancedSettingsFrame = Frame {
 }
 IsEnabled = <function> defined @DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:447
 CreateGroup = <function> defined @Rarity_Options/Options.lua:1723
 ScheduleTimer = <function> defined @DataStore/libs/AceTimer-3.0/AceTimer-3.0.lua:94
 ShowQuicktip = <function> defined @Rarity/Core/GUI/MainWindow.lua:77
 OnBagUpdate = <function> defined @Rarity/Core/EventHandlers.lua:1077
 RegisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RegisterSink = <function> defined @Rarity/Libs/LibSink-2.0/LibSink-2.0/LibSink-2.0.lua:800
 ProfileStart2 = <function> defined @Rarity/Core/Debugging.lua:31
 tempbagitems = <table> {
 }
 db = <table> {
 }
 guids = <table> {
 }
 NewBarGroup = <function> defined @Rarity/Libs/LibBars-1.0/LibBars-1.0.lua:331
 GetNPCIDFromGUID = <function> defined @Rarity/Core.lua:649
 bar = Frame {
 }
 EventHandlers = <table> {
 }
 architems = <table> {
 }
 itemsMasterList = <table> {
 }
 GetBars = <function> defined @Rarity/Libs/LibBars-1.0/LibBars-1.0.lua:222
 toysScanned = true
 Options_DoEnable = <function> defined @Rarity_Options/Options.lua:90
 UpdateInterestingThings = <function> defined @Rarity/Core.lua:473
 Encode = <function> defined @Rarity/Core/Serialization.lua:229
 OnQuestTurnedIn = <function> defined @Rarity/Core/EventHandlers.lua:439
 relevantSpells = <table> {
 }
 NewCounterBar = <function> defined @Rarity/Libs/LibBars-1.0/LibBars-1.0.lua:280
 holiday_textures = <table> {
 }
 OnInitialize = <function> defined @Rarity/Core.lua:142
 UnregisterAllEvents = <function> defined @AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 options = <table> {
 }
 npcs_to_items = <table> {
 }
 isHorde = false
 isAlliance = true
 ach_npcs_achId = <table> {
 }
 npcs = <table> {
 }
 items_with_stats = <table> {
 }
 IsCollectionItem = <function> defined @Rarity/Core/EventHandlers.lua:994
 optionsFrame = Frame {
 }
 Deserialize = <function> defined @DataStore/libs/AceSerializer-3.0/AceSerializer-3.0.lua:246
 lastStatCount = 0
 isFishing = false
 ProfileDebug = <function> defined @Rarity/Core/Debugging.lua:51
 OnCriteriaComplete = <function> defined @Rarity/Core/EventHandlers.lua:599
 OnSpellcastSucceeded = <function> defined @Rarity/Core/EventHandlers.lua:145
 GetName = <function> defined @Da

**Comment by Ookami313** [comment]
Had a second error that was occurring that I though was related to another addon I use, but when I disable Rarity the error does not pop with a reload. Re-enabling Rarity and reloading, the error occurs.

4x AceEvent30Frame:RegisterEvent(): AceEvent30Frame:RegisterEvent(): Attempt to register unknown event "RESEARCH_ARTIFACT_HISTORY_READY"
[string "=[C]"]: in function `RegisterEvent'
[string "@DataStore/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:33: in function `OnUsed'
[string "@AllTheThings/lib/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:132: in function `RegisterEvent'
[string "@Rarity/Core/EventHandlers.lua"]:75: in function `Register'
[string "@Rarity/Core.lua"]:188: in function `DoEnable'
[string "@Rarity/Core.lua"]:150: in function <Rarity/Core.lua:149>
[string "=[C]"]: ?
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@DataStore/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <DataStore/libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:544: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:753: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:175: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:168: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:163: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:154: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:150>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:118: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals:
(*temporary) = AceEvent30Frame {
 0 = <userdata>
}
(*temporary) = "RESEARCH_ARTIFACT_HISTORY_READY"

**Comment by Hollicsh** [comment]
++
Same

**Comment by elkewtf** [comment]
I submitted a pull request that fixes the issues with the 10.1.5 update.

**Comment by Duckwhale** [comment]
Fixed via https://github.com/WowRarity/Rarity/pull/559 - thanks again, @elkewtf !
