### ISSUE TITLE
Add Drakewatcher Manuscript "Highland Drake: Embodiment of the Hellforged"

### ISSUE THREAD

**Issue by Unplayed** [WowRarity/Rarity#561]
Id: 205876

NPC: 205319

Statistics ID: 18187,18198,18218,18227

**Comment by Duckwhale** [comment]
Wouldn't it be more appropriate to create import strings for this (and other manuscripts)? I don't know if they need to be built in.

**Comment by Duckwhale** [comment]
If there's interest in these, someone can create a set of export strings and post it on Discord/Curse, just like we have for illusions.

**Comment by cyriun** [comment]
yeah its pretty much just how they're doing raid and gladiator mounts in dragonflight, a skin for the existing base dragonriding mounts
