### ISSUE TITLE
Add Dragonflight 10.1.5 mounts to the database

### ISSUE THREAD

**Issue by godejord** [WowRarity/Rarity#566]
The following mounts were added in patch 10.1.5 and should be tracked by Rarity. All of these mounts are from the same event. Source for the list is [warcraftmounts.com](https://www.warcraftmounts.com/patch10.1.5.php)

All mounts seem to drop both from completing the event, as well as being able to drop from a container. Aka we have two sources here, which is generally an issue for Rarity

- [x] [Reins of the Scourgebound Vanquisher](https://www.wowhead.com/ptr-2/item=206680/reins-of-the-scourgebound-vanquisher)
- [x] [Perfected Juggernaut](https://www.wowhead.com/ptr-2/item=206679/perfected-juggernaut)
- [x] [Felstorm Dragon](https://www.wowhead.com/ptr-2/item=206676/felstorm-dragon)
- [x] [Sulfur Hound's Leash](https://www.wowhead.com/ptr-2/item=206678/sulfur-hounds-leash)
- [ ] [Reins of the Ravenous Black Gryphon](https://www.wowhead.com/ptr-2/item=206674/reins-of-the-ravenous-black-gryphon) Alliance Only
- [ ] [Horn of the White War Wolf](https://www.wowhead.com/ptr-2/item=206673/horn-of-the-white-war-wolf) Horde Only
- [x] [Gold-Toed Albatross](https://www.wowhead.com/ptr-2/item=206675/gold-toed-albatross)

**Comment by Duckwhale** [comment]
The info on wowhead suggests these drop from a container, but purchasing them via currency is also possible? If that's correct, any reason to not just add the container drop and ignore the alternative method? It's probably better than not tracking them at all.

**Comment by godejord** [comment]
All of them can drop from container and be purchased via currency, yes. Some of the Wowhead comments indicated that they could also drop directry off the bosses associated with the event (not via container). I am not sure if that last bit was a PTR only thing, or if that is still possible on live servers. If it can drop from the bosses too, then we should probably find out which is the primary way of obtaining/grinding these? That being said, I fully support adding tracking to the containers for the time being regardless

**Comment by Duckwhale** [comment]
OK, I'll just add them as a drop from the container (for now). I've no way to test ingame though (no max level character).

**Comment by Duckwhale** [comment]
As for the boss drops, maybe we can add support for this via "SPECIAL"-like event handling code? It's not clean but it might work.

The alternative would be modifying the detection system to support multiple item sources, which sounds like a headache.

**Comment by Duckwhale** [comment]
I can't see any indication on wowhead that the faction-specific mounts would drop from the container, so I'll omit them.
