### ISSUE TITLE
Rarity throws error on login involving RESEARCH_ARTIFACT_HISTORY_READY which seems to be obsolete in 10.1.5

### ISSUE THREAD

**Issue by SnoozingDormouse** [WowRarity/Rarity#570]
On loading rarity there is an error thrown trying to register EVENT RESEARCH_ARTIFACT_HISTORY_READY and also calling RequestArtifactCompletionHistory()

**Comment by SnoozingDormouse** [comment]
I see this was fixed a few weeks ago but the version on Curseforge is from Nov 22, 2022.  Is this being distributed there still?

**Comment by Duckwhale** [comment]
Yes, it's included in the latest alpha version. I haven't yet created a proper release, but you can select the alpha channel manually.

**Comment by Duckwhale** [comment]
(Duplicate of #557)
