### ISSUE TITLE
Add tracking for Everlasting Horn of Lavaswimming

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#582]
This here: [Everlasting Horn of Lavaswimming](https://www.wowhead.com/item=200116/everlasting-horn-of-lavaswimming)

Follow-up for #514 - no idea how it should be tracked currently.

**Comment by cyriun** [comment]
i can add this along with some other 10.0 toys that are still missing, if any. Im going to abandon (for now) trying to figure out how to track the event and just add tracking upon killing the mob at the end of the event.

**Comment by Duckwhale** [comment]
I tried to add all of the toys I could find on wowhead - there shouldn't be any missing unless there's an issue (or I didn't see it) :D

If you do find something, of course feel free to add it! Just a heads-up so you can double-check as I've added lots of items recently.

**Comment by cyriun** [comment]
yeah that was the last one, as you mentioned i believe there are 2 others but they have basically no data on wowhead

**Comment by Duckwhale** [comment]
Also, for a better detection I think it might be possible to track the event using these:

* [Event: SCENARIO_COMPLETED](https://wowpedia.fandom.com/wiki/SCENARIO_COMPLETED)
* [Quest: Scalebane Keep](https://www.wowhead.com/quest=70867/scalebane-keep)

As far as I can see, there's no handler for this event yet. But it might be worth trying to add one and see if that'll do the trick.

**Comment by cyriun** [comment]
yea previously when i was trying to track it that way it triggered a quest id everytime but its abit out of my depth, i couldnt get it to work

**Comment by Duckwhale** [comment]
I suppose it would be similar to [how Island Expeditions are handled](https://github.com/WowRarity/Rarity/blob/c3d92570b2e9e8fcf186417185d47b71f55347d3/Core/EventHandlers.lua#L460-L584):

* Create a new event listener (function)
* Inside it, add an attempt for the item if it's enabled/not obtained

Does that sound reasonable? Or what did you try that wasn't working?

**Comment by cyriun** [comment]
ill take a look at islands then, but i pretty much found something i thought could be similar to it and referenced that but i dont quite remember what it was, i'd have to look again
