### ISSUE TITLE
Add Dragonflight 10.2.0 mounts to the database

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#651]
Roadmap:

- [x] Review https://www.wowhead.com/ptr-2/items/miscellaneous/mounts?filter=82;3;100200
- [x] Determine which items are relevant (and which are TBD/need more data)
- [ ] Add tracking for the relevant mounts
  - [ ] [Reins of the Winter Night Dreamsaber](https://www.wowhead.com/item=210059/reins-of-the-winter-night-dreamsaber)
  - [ ] [Reins of the Snowfluff Dreamtalon](https://www.wowhead.com/item=210775/reins-of-the-snowfluff-dreamtalon)
  - [ ] [Reins of the Evening Sun Dreamsaber](https://www.wowhead.com/item=210058/reins-of-the-evening-sun-dreamsaber)
  - [ ] [Reins of the Blossoming Dreamstag](https://www.wowhead.com/item=209947/reins-of-the-blossoming-dreamstag)
  - [ ] [Reins of the Springtide Dreamtalon](https://www.wowhead.com/item=210769/reins-of-the-springtide-dreamtalon)
  - [ ] [Reins of the Morning Flourish Dreamsaber](https://www.wowhead.com/item=210057/reins-of-the-morning-flourish-dreamsaber)
  - [ ] [Reins of the Rekindled Dreamstag](https://www.wowhead.com/item=209950/reins-of-the-rekindled-dreamstag)

Note: Some of those mounts can also be purchased from a vendor (i.e., they need the corresponding `sourceText`).

**Comment by Duckwhale** [comment]
Partially resolved by #679 - although the other mounts would have to be added separately (using the same event handler).

**Comment by cyriun** [comment]
so the rest of these mounts also drop from the cache but can also be purchased?

**Comment by Duckwhale** [comment]
> so the rest of these mounts also drop from the cache but can also be purchased?

According to wowhead data, yeah. I haven't verified this in any way, however. One oddity I've noticed with the other mounts is that the number of seeds is much smaller in those cases, which may indicate they don't drop from all of them? Alternatively, it could just be an issue of low sample size, i.e., wowhead just doesn't have enough data yet because the drop rate is lower.

**Comment by cyriun** [comment]
for these mounts looks like we have to determine if the current dreamseed bloom is from a gigantic dreamseed or instead hopefully the gigantic dreamseed blooms have specific dreamseed caches

**Comment by cyriun** [comment]
#683 new pr 99% resolving this

**Comment by Duckwhale** [comment]
> #683 new pr 99% resolving this

What's the last 1%? If it's related to the GameObject ID, we can probably implement a filtering mechanism based on it?

**Comment by cyriun** [comment]
> > #683 new pr 99% resolving this
> 
> What's the last 1%? If it's related to the GameObject ID, we can probably implement a filtering mechanism based on it?

yeah that but are we sure that the epic seed caches have specific ids?

**Comment by Duckwhale** [comment]
I'm not sure of anything. We'd have to gather the IDs first and see if that's the case.
