### ISSUE TITLE
Primal Storm events aren't detected (attempts for the relevant pets are always added)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#655]
Rarity currently adds attempt for these pets regardless of whether or not a Primal Storm event is active in the area.

This was clearly an oversight on my part, though it wasn't reported as a problem so far. Hopefully no one spent too much time killing things that couldn't actually drop the items... oh well. Depending on how difficult it would be to detect Primal Storms, it might not be worth spending too much time on fixing this if no one has complained yet...?

---

Follow-up to #516

**Comment by Duckwhale** [comment]
For reference: https://www.wowhead.com/guide/primal-storms-dragonflight

**Comment by cyriun** [comment]
there is a buff enemies gain called "Elementally Imbued"

**Comment by Duckwhale** [comment]
Thanks! Then it should be simple to add, though I'm not sure which of these needs to be tracked:

* https://www.wowhead.com/search?q=Elementally+Imbued

Can probably track these via [UNIT_AURA](https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentation#UNIT_AURA) event, or use the [C_UnitAuras.GetAuraDataBySlot](https://www.townlong-yak.com/framexml/live/Blizzard_APIDocumentation#C_UnitAuras.GetAuraDataBySlot) API, with [UnitAuraSlots](https://wowpedia.fandom.com/wiki/API_UnitAuraSlots)?

**Comment by cyriun** [comment]
from looking around it looks like 90% of the mobs have the buff, im assuming the mobs that are already in those areas when theres no elemental storm gain the buff and mobs spawn when the elemental storm is active dont have the buff. not sure on this so will have too check after the storm goes

**Comment by cyriun** [comment]
check #659
