### ISSUE TITLE
Add tracking for Brul

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#674]
[This pet](https://www.wowhead.com/item=205114/brul) requires opening the [Chest of Massive Gains](https://www.wowhead.com/object=398828/chest-of-massive-gains) while having the [aura](https://www.wowhead.com/spell=407063/rocks-on-the-rocks) from [Rocks on the Rocks](https://www.wowhead.com/item=204845/rocks-on-the-rocks) active.

**Comment by cyriun** [comment]
i believe this can be added similar to the primal storm pets right? just that the current section of `IsAttemptAllowed` function has to be reworked a little

**Comment by cyriun** [comment]
but also would it use special detection method since its a chest?

**Comment by cyriun** [comment]
going off wowhead comments this seems like its gonna be a pain to test
