### ISSUE TITLE
Search functionality in Appearance tab is blocked (tainted) (?)

### ISSUE THREAD

**Issue by Duckwhale** [WowRarity/Rarity#69]
Source: [WowAce](https://www.wowace.com/projects/rarity/issues/326)
> Rarity disable the search feature in Appearances Version R681
I have disabled all the addons and this problem only occurs with Rarity enabled. Search works fine in the Mount tab, pet tab, Toy box and heirlooms. Only problem is in the appearance tab.

**Comment by godejord** [comment]
Not sure if this was ever addressed, or something that just resolved itself, but I haven't been able to reproduce this problem. Nor can I say that I have ever encountered it before..

**Comment by Duckwhale** [comment]
Yeah, in order to debug this we'd probably need a taint log. I haven't experienced this myself either.
