### ISSUE TITLE
Update Seaborne Spore (pet) drop chance

### ISSUE THREAD

**Issue by Taizunz** [WowRarity/Rarity#701]
It currently tracks as if the chance is 1/33 like the other pets that can be acquired from the same legendary pet battles, but comments on wowhead all point towards this being closer to 1/333 in reality.

https://www.wowhead.com/item=118105/seaborne-spore#comments

**Comment by Duckwhale** [comment]
Thanks! I'll update the drop rate before publishing the next release.
