### ISSUE TITLE
Assertion failure in GameTooltipHooks.lua after today's release (r734)

### ISSUE THREAD

**Issue by dblanch369** [WowRarity/Rarity#740]
First time I've seen an error come from Rarity in some time... but after today's update, I randomly got this.... Possibly related to the changed noted in changelog?

1x Rarity/Core/GUI/GameTooltipHooks.lua:524: Failed to extract item ID from item link (format might have changed?)
[string "=[C]"]: in function `assert'
[string "@Rarity/Core/GUI/GameTooltipHooks.lua"]:524: in function <Rarity/Core/GUI/GameTooltipHooks.lua:513>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1533: in function `OnUpdate'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1492: in function `OnEnter'
[string "@Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua"]:1488: in function <...s/Blizzard_UIPanels_Game/Mainline/ContainerFrame.lua:1487>
[string "=[C]"]: ?

Locals:
(*temporary) = nil
(*temporary) = "Failed to extract item ID from item link (format might have changed?)"

**Comment by dblanch369** [comment]
Ok a little more information.  I can replicate the error when I mouse over a Mythic Keystone in my bag.

**Comment by Hollicsh** [comment]
Yep. Same.

**Comment by Duckwhale** [comment]
Is it only happening with Mythic keystones? Please check the `itemLink = ...` part, for example (from Discord):

```lua
itemLink = "|cffa335ee|Hkeystone:180653:406:9:9:135:0:0|h[Keystone: Halls of Infusion (9)]|h|r"
```

I figured there might be a problem with the simple matching pattern, hence the assertion that has failed here.

I'll have to look into this tomorrow. If anyone gets this error but NOT from keystones, please report it here or on Discord.

**Comment by Duckwhale** [comment]
If you need the addon to "just work" urgently, feel free to revert to the previous release. This was merely a performance upgrade.

**Comment by dblanch369** [comment]
Urgent? not for me. Other than bug sack making that wonderful "Fatality" noise ;). No, I was just doing my part and reporting a bug.  If it does occur on any other items, I will certainly let you know!
