### ISSUE TITLE
Script Ran too long error v735

### ISSUE THREAD

**Issue by CrusaderEsper** [WowRarity/Rarity#753]
Had Rarity kick out this error to me. I had recently logged in and went straight into a Delve. This popped up a few minutes into the delve.

<details>
<summary>Extremely verbose error message</summary>
1x Rarity/Core/Collections.lua:196: script ran too long
[string "@Rarity/Core/Collections.lua"]:196: in function `ScanExistingItems'
[string "@Rarity/Core.lua"]:322: in function `func'
[string "@Broker_uClock/Lib/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <...dOns/Broker_uClock/Lib/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = <table> {
 lockouts_detailed = <table> {
 }
 modules = <table> {
 }
 string_methods = <table> {
 }
 advancedSettings = <table> {
 }
 Testing = <table> {
 }
 isGuildBankOpen = false
 AddonCompartment = <table> {
 }
 bagitems = <table> {
 }
 advancedSettingsFrame = Frame {
 }
 HolidayEvents = <table> {
 }
 foundTarget = false
 tempbagitems = <table> {
 }
 db = <table> {
 }
 guids = <table> {
 }
 toysScanned = true
 mount_sources = <table> {
 }
 catIcons = <table> {
 }
 isHorde = false
 isAlliance = true
 options = <table> {
 }
 lastStatCount = 48
 EventHandlers = <table> {
 }
 architems = <table> {
 }
 itemsMasterList = <table> {
 }
 bar = Frame {
 }
 defaults = <table> {
 }
 relevantSpells = <table> {
 }
 holiday_textures = <table> {
 }
 npcs_to_items = <table> {
 }
 itemInfoCache = <table> {
 }
 ach_npcs_achId = <table> {
 }
 npcs = <table> {
 }
 items_with_stats = <table> {
 }
 optionsFrame = Frame {
 }
 itemsToPrime = <table> {
 }
 isFishing = false
 string_types = <table> {
 }
 name = "Rarity"
 ItemDB = <table> {
 }
 used = <table> {
 }
 Statistics = <table> {
 }
 DatabaseSchema = <table> {
 }
 modulesEnabled = <table> {
 }
 isOpening = false
 lockouts_holiday = <table> {
 }
 string_archraces = <table> {
 }
 isPool = false
 Announcements = <table> {
 }
 isTradeskillOpen = false
 Database = <table> {
 }
 isTradeWindowOpen = false
 Caching = <table> {
 }
 baseName = "Rarity"
 pet_sources = <table> {
 }
 Collections = <table> {
 }
 Enum = <table> {
 }
 lockouts = <table> {
 }
 profileOptions = <table> {
 }
 CONSTANTS = <table> {
 }
 defaultModuleState = true
 CopyPastePopup = <table> {
 }
 MapInfo = <table> {
 }
 Waypoints = <table> {
 }
 Validation = <table> {
 }
 Tracking = <table> {
 }
 zones = <table> {
 }
 opennodes = <table> {
 }
 Profiling = <table> {
 }
 GUI = <table> {
 }
 enabledState = true
 tooltipOpenDelay = false
 stats_to_scan = <table> {
 }
 profileFrame = Frame {
 }
 Debugging = <table> {
 }
 isAuctionHouseOpen = false
 ScrollingDebugMessageFrame = <table> {
 }
 fishnodes = <table> {
 }
 items_to_items = <table> {
 }
 isMailboxOpen = false
 Item = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 Serialization = <table> {
 }
 Output = <table> {
 }
 fishzones = <table> {
 }
 items = <table> {
 }
 orderedModules = <table> {
 }
 isBankOpen = false
 ach_npcs_isKilled = <table> {
 }
 Tooltips = <table> {
 }
 coins = <table> {
 }
 Utils = <table> {
 }
 MINOR_VERSION = 735
 AuctionDB = <table> {
 }
 AreaPOIs = <table> {
 }
 barGroup = Frame {
 }
 collection_items = <table> {
 }
 miningnodes = <table> {
 }
 bosses = <table> {
 }
 Session = <table> {
 }
}
reason = "FINAL INIT"
total = 2272
numOwnedPets = 1983
(for index) = 169
(for limit) = 2272
(for step) = 1
i = 169
petID = "BattlePet-0-000003CFACD5"
speciesID = 1563
owned = true
customName = nil
level = 25
favorite = false
isRevoked = false
speciesName = "Bronze Whelpling"
icon = 134156
petType = 2
companionID = 7546
tooltip = "|cFFFFD200Drop: |rIron Horde|n|cFFFFD200Zone: |rBlasted Lands"
description = "The Bronze Whelpling was lost in time until an unusual event allowed her to escape."
isWild = false
canBattle = true
isTradeable = true
isUnique = false
obtainable = true
(for state) = <table> {
 pets = <table> {
 }
 items = <table> {
 }
 mounts = <table> {
 }
 user = <table> {
 }
}
(for control) = "pets"
k = "pets"
v = <table> {
 Snarly's Bucket = <table> {
 }
 Skaarn = <table> {
 }
 Teardrop Moth = <table> {
 }
 Spiky Collar = <table> {
 }
 Bone Serpent = <table> {
 }
 Geordy = <table> {
 }
 Corpselouse Larva = <table> {
 }
 Mischievous Zephyr = <table> {
 }
 Shy Melvin = <table> {
 }
 Orphaned Felbat = <table> {
 }
 Luvvy = <table> {
 }
 Rattling Bones = <table> {
 }
 Servant of Demidos = <table> {
 }
 Dark Quivering Blob = <table> {
 }
 Sandshell Chitterer = <table> {
 }
 Fandral's Pet Carrier = <table> {
 }
 Vibrating Arcane Crystal = <table> {
 }
 Tiny Amber Wings = <table> {
 }
 Ridged Shalewing = <table> {
 }
 Call of the Frozen Blade = <table> {
 }
 Slithershock Elver = <table> {
 }
 Parrot Cage (Green Wing Macaw) = <table> {
 }
 C'Thuffer 
 </details>

**Comment by Duckwhale** [comment]
Thank you for the report. Unfortunately, it is too unspecific to be actionable.

This error could be triggered by any number of things, most of which are outside of the addon developer's control. If it's a recurring problem, I'd start with disabling all other addons, making sure your machine has enough resources available, and then try to narrow down under which exact, reproducible circumstances the error manifests. And even then, maybe your PC is just too slow?

I'll close this issue for the time being, but feel free to report back should more information become available.
